### ISSUE TITLE
build task is compiling the demo app

### ISSUE THREAD

**Issue by MurhafSousli** [robisim74/angular-library-starter#14]
Including a demo app inside the project causes the build to fail. Is there a way to skip building from the demo directory?

for example when I added my demo app to the project, I get this
```
Start building...
Start TSLint
Error at demo/e2e/app.po.ts:1:38: Cannot find module 'protractor'.
Error at demo/src/app/app.module.ts:3:29: Cannot find module '@angular/forms'.
Error at demo/src/app/app.module.ts:5:34: Cannot find module 'ngx-progressbar'.
Error at demo/src/app/main/main.component.spec.ts:8:21: Supplied parameters do not match any signature of call target.
Error at demo/src/app/main/main.component.ts:2:33: Cannot find module 'ngx-progressbar'.
```

**Comment by robisim74** [comment]
The building process uses only `src` folder. About TSLint, you have more options: you can add _demo_ to the _exclude_ section of _tsconfig.json_:
```
    "exclude": [
        "node_modules",
        "demo"
    ]
```
or change the _exec_ command in _build.js_.

**Comment by MurhafSousli** [comment]
Problem solved, Thank you.
