### ISSUE TITLE
Uncaught Error: Unexpected value 'ArithmeticModule' imported by the module 'AppModule'. Please add a @NgModule annotation

### ISSUE THREAD

**Issue by jjlgjkkl** [robisim74/angular-library-starter#15]
In  angular4.2.4,  getting this error
when running npm start (ng server), the building process is ok, but getting this error in the browser
my app.module.ts
import {ArithmeticModule} from 'angular-library-starter';
@NgModule({
  declarations: [
    AppComponent, HelloComponent
  ],
  imports: [
    BrowserModule, routing, ArithmeticModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

error stack from browser
Uncaught Error: Unexpected value 'ArithmeticModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:19702:34)
    at http://localhost:4200/vendor.bundle.js:33386:44
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:33369:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:44692:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:44665:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:44594:37)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:50335:25)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:50321:21)
    at Object.../../../../../src/main.ts (http://localhost:4200/main.bundle.js:17877:124)

**Comment by robisim74** [comment]
Maybe you got something wrong with the versions: https://github.com/angular/angular/issues/15763

**Comment by jjlgjkkl** [comment]
I really appreciate for your reply.
I checked and tried, still the same exception.
I only simplely download your code and   then run "ng run build".
Then, using angular cli 1.1.0 ,"ng new" a new project, and then execute "npm i d:\angular-library-starter-master\dist".
Next ,executting "npm start", the error occurs in the browsser. but the build process is ok.
If executting in aot mode(ng serve --aot),everything goes OK.

**Comment by robisim74** [comment]
`ng run build`, `npm i d:\angular-library-starter-master\dist`: where did you find those commands? Please follow the instructions in the README on how to use this starter. Greetings

**Comment by jjlgjkkl** [comment]
thank you very much!!!
wow, it's OK now.
but , i still have no idea what's the difference between  npm i d:\angular-library-starter-master\dist and d:\angular-library-starter-master.tgz
but ,whatever
thank you again!

**Comment by antlaij** [comment]
Hi @robisim74 ,
I am having the same problem.
After I did npm i d:\angular-library-starter-master\dist
It works. Thank you
I have also try using npm link to add the dist folder to my project.
I have got the same error again.
Can you tell me what it the different between npm install and npm link?
Thanks

**Comment by robisim74** [comment]
@antlaij  about _npm link_ see this issue: #2 To use it with webpack, you need to change the configuration of webpack, and with _Angular-cli_ for example you can not do it.
Using _npm pack_, instead, you simulate the real installation.
Greetings
