### ISSUE TITLE
Could not resolve entry module

### ISSUE THREAD

**Issue by Eutrepe** [robisim74/angular-library-starter#64]
Node - v10.16.3
npm - 6.13.1
Angular CLI: 8.3.19
Angular: v8.x

Sometimes after build package I have ```Error: Could not resolve entry module (dist/fesm5/angular-library-starter.js).``` I have the same error in your boilerplate  even without any changes. How can I fix it?

```
> angular-library-starter@0.0.1 build /vagrant/angular-library-starter
> node build.js

Start building...
Start TSLint
TSLint completed
Try to process scss files
Rendering Complete, saving .css file...
Wrote CSS to /vagrant/angular-library-starter/dist/package/src/components/sum.component.css
Wrote 1 CSS files to /vagrant/angular-library-starter/dist/package
Start AoT compilation
AoT compilation completed
Copy ES2015 for package
Start bundling
Rollup package

dist/angular-library-starter.js → dist/fesm2015/angular-library-starter.js...
created dist/fesm2015/angular-library-starter.js in 84ms
Produce ESM5/FESM5 versions

dist/package/esm5/angular-library-starter.js → dist/fesm5/angular-library-starter.js...
created dist/fesm5/angular-library-starter.js in 93ms
Run Rollup conversion on package

dist/fesm5/angular-library-starter.js → dist/bundles/angular-library-starter.umd.js...
[!] Error: Could not resolve entry module (dist/fesm5/angular-library-starter.js).
Error: Could not resolve entry module (dist/fesm5/angular-library-starter.js).
    at error (/vagrant/angular-library-starter/node_modules/rollup/dist/rollup.js:9230:30)
    at pluginDriver.hookFirst.then (/vagrant/angular-library-starter/node_modules/rollup/dist/rollup.js:15752:20)

Error: Rollup conversion failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-library-starter@0.0.1 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-library-starter@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by robisim74** [comment]
This is not a problem with this starter, but something incompatible in the library. Please look for similar issues on SO.
